USE [master]
GO

/****** Object:  Database [gart]    Script Date: 05/11/2020 9:31:06 PM ******/
CREATE DATABASE [gart]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'gart', FILENAME = N'C:\Users\alina\Desktop\tw2020-master\database\gart.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'gart_log', FILENAME = N'C:\Users\alina\Desktop\tw2020-master\database\gart_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [gart].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [gart] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [gart] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [gart] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [gart] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [gart] SET ARITHABORT OFF 
GO

ALTER DATABASE [gart] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [gart] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [gart] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [gart] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [gart] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [gart] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [gart] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [gart] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [gart] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [gart] SET  DISABLE_BROKER 
GO

ALTER DATABASE [gart] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [gart] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [gart] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [gart] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [gart] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [gart] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [gart] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [gart] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [gart] SET  MULTI_USER 
GO

ALTER DATABASE [gart] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [gart] SET DB_CHAINING OFF 
GO

ALTER DATABASE [gart] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [gart] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [gart] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [gart] SET QUERY_STORE = OFF
GO

USE [gart]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [gart] SET  READ_WRITE 
GO


